Feature/dashboard
devaneios-ifsp/turma-de-elite-backend pull request #45
Opened 2021-11-08 02:04 UTC by biancahng

Back-end dos dashboards de administrador

2021-11-08 02:06 UTC, NatanLisboa approved these changes

2021-12-04 12:22 UTC, AndreM-Gomes requested changes

2021-12-04 12:22 UTC, AndreM-Gomes commented on .jpb/persistence-units.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Configuração de projetos Spring Boot é  feito no applications.yaml ou por anotações. Configuração por XML é a forma antiga de se fazer

2021-12-04 12:22 UTC, AndreM-Gomes commented on src/main/java/com/devaneios/turmadeelite/controllers/StudentController.java
> +    @GetMapping("activeInactive")
Nomeação dos endpoints normalmente é feito em kebab-case. Neste projeto está sendo feito em kebab-case (se algum estiver diferente, já alterar por favor.
https://betterprogramming.pub/string-case-styles-camel-pascal-snake-and-kebab-case-981407998841

2021-12-04 12:22 UTC, AndreM-Gomes commented on src/main/java/com/devaneios/turmadeelite/external/classroom/activities/ActivitiesService.java
> +                                    .punctuation(classroomActivities.getMaxPoints())
Max points seria a nota máxima que poderia ser tirada. Eu acho que a pontuação seria assignedGrade / maxPoints. Conferir documentação da API

2021-12-04 12:22 UTC, AndreM-Gomes commented on src/main/java/com/devaneios/turmadeelite/external/classroom/authentication/AuthenticationController.java
> +        return new RedirectView("http://localhost:4200?authenticationSuccess=true");
Externalizar a url para o arquivo de configuração. Se não souber/não quiser fazer, por favor lembrar antes do deploy (se não, não vai funcionar em produção)

2021-12-04 12:22 UTC, AndreM-Gomes commented on src/main/java/com/devaneios/turmadeelite/external/classroom/courses/CoursesService.java
> +    public List<SchoolClassViewDTO> getCoursesFromTeacher(String authUuid) throws IOException {
Não fazer push de métodos vazios

2021-12-05 00:42 UTC, merged